"""
유명 투자자들의 투자 기준 정의
각 전략은 yfinance 필드명과 최소/최대 기준값을 가짐
"""

STRATEGIES = {
    "buffett": {
        "name": "Warren Buffett",
        "korean_name": "워런 버핏",
        "description": "경제적 해자를 가진 우량 기업을 합리적 가격에 매수 (Quality Value)",
        "style": "Quality Value",
        "color": "gold1",
        "criteria": [
            {
                "name": "ROE",
                "field": "roe",
                "min": 0.15,
                "max": None,
                "weight": 2.0,
                "description": "자기자본이익률(ROE) ≥ 15%",
                "format": ".1%",
            },
            {
                "name": "P/E",
                "field": "pe",
                "min": 0,
                "max": 25,
                "weight": 1.5,
                "description": "주가수익비율(PER) 0 ~ 25",
                "format": ".1f",
            },
            {
                "name": "P/B",
                "field": "pb",
                "min": 0,
                "max": 3.0,
                "weight": 1.5,
                "description": "주가순자산비율(PBR) ≤ 3.0",
                "format": ".2f",
            },
            {
                "name": "부채비율",
                "field": "debt_to_equity",
                "min": None,
                "max": 50,
                "weight": 1.5,
                "description": "부채비율(D/E) ≤ 50%",
                "format": ".1f",
            },
            {
                "name": "순이익마진",
                "field": "profit_margins",
                "min": 0.10,
                "max": None,
                "weight": 1.5,
                "description": "순이익률 ≥ 10%",
                "format": ".1%",
            },
            {
                "name": "EPS성장률",
                "field": "earnings_growth",
                "min": 0.05,
                "max": None,
                "weight": 1.0,
                "description": "EPS 성장률 ≥ 5%",
                "format": ".1%",
            },
        ],
    },
    "graham": {
        "name": "Benjamin Graham",
        "korean_name": "벤자민 그레이엄",
        "description": "내재가치 대비 충분한 안전마진 확보 (Deep Value)",
        "style": "Deep Value",
        "color": "green",
        "criteria": [
            {
                "name": "P/E",
                "field": "pe",
                "min": 0,
                "max": 15,
                "weight": 2.0,
                "description": "주가수익비율(PER) ≤ 15",
                "format": ".1f",
            },
            {
                "name": "P/B",
                "field": "pb",
                "min": 0,
                "max": 1.5,
                "weight": 2.0,
                "description": "주가순자산비율(PBR) ≤ 1.5",
                "format": ".2f",
            },
            {
                "name": "유동비율",
                "field": "current_ratio",
                "min": 2.0,
                "max": None,
                "weight": 1.5,
                "description": "유동비율(Current Ratio) ≥ 2.0",
                "format": ".2f",
            },
            {
                "name": "부채비율",
                "field": "debt_to_equity",
                "min": None,
                "max": 100,
                "weight": 1.5,
                "description": "부채비율(D/E) ≤ 100%",
                "format": ".1f",
            },
            {
                "name": "배당수익률",
                "field": "dividend_yield",
                "min": 0.02,
                "max": None,
                "weight": 1.0,
                "description": "배당수익률 ≥ 2%",
                "format": ".1%",
            },
            {
                "name": "ROE",
                "field": "roe",
                "min": 0.08,
                "max": None,
                "weight": 1.0,
                "description": "ROE ≥ 8%",
                "format": ".1%",
            },
        ],
    },
    "lynch": {
        "name": "Peter Lynch",
        "korean_name": "피터 린치",
        "description": "합리적 가격의 성장주 발굴 GARP (Growth At Reasonable Price)",
        "style": "GARP",
        "color": "cyan",
        "criteria": [
            {
                "name": "PEG",
                "field": "peg",
                "min": 0,
                "max": 1.0,
                "weight": 3.0,
                "description": "PEG 비율 ≤ 1.0 (핵심 지표)",
                "format": ".2f",
            },
            {
                "name": "P/E",
                "field": "pe",
                "min": 0,
                "max": 30,
                "weight": 1.5,
                "description": "주가수익비율(PER) ≤ 30",
                "format": ".1f",
            },
            {
                "name": "EPS성장률",
                "field": "earnings_growth",
                "min": 0.15,
                "max": None,
                "weight": 2.0,
                "description": "EPS 성장률 ≥ 15%",
                "format": ".1%",
            },
            {
                "name": "부채비율",
                "field": "debt_to_equity",
                "min": None,
                "max": 35,
                "weight": 1.0,
                "description": "부채비율(D/E) ≤ 35%",
                "format": ".1f",
            },
            {
                "name": "ROE",
                "field": "roe",
                "min": 0.15,
                "max": None,
                "weight": 1.5,
                "description": "ROE ≥ 15%",
                "format": ".1%",
            },
        ],
    },
    "greenblatt": {
        "name": "Joel Greenblatt",
        "korean_name": "조엘 그린블라트",
        "description": "높은 이익수익률 + 높은 자본이익률 (Magic Formula)",
        "style": "Magic Formula",
        "color": "magenta",
        "criteria": [
            {
                "name": "EV/EBITDA",
                "field": "ev_ebitda",
                "min": 0,
                "max": 12,
                "weight": 2.0,
                "description": "EV/EBITDA ≤ 12 (이익수익률)",
                "format": ".1f",
            },
            {
                "name": "ROE",
                "field": "roe",
                "min": 0.20,
                "max": None,
                "weight": 2.0,
                "description": "ROE ≥ 20% (자본이익률)",
                "format": ".1%",
            },
            {
                "name": "P/E",
                "field": "pe",
                "min": 0,
                "max": 20,
                "weight": 1.5,
                "description": "PER ≤ 20",
                "format": ".1f",
            },
            {
                "name": "순이익마진",
                "field": "profit_margins",
                "min": 0.15,
                "max": None,
                "weight": 1.5,
                "description": "순이익률 ≥ 15%",
                "format": ".1%",
            },
        ],
    },
    "fisher": {
        "name": "Philip Fisher",
        "korean_name": "필립 피셔",
        "description": "탁월한 성장 잠재력을 가진 기업에 장기 투자 (Growth)",
        "style": "Growth",
        "color": "blue",
        "criteria": [
            {
                "name": "매출성장률",
                "field": "revenue_growth",
                "min": 0.10,
                "max": None,
                "weight": 2.0,
                "description": "매출 성장률 ≥ 10%",
                "format": ".1%",
            },
            {
                "name": "EPS성장률",
                "field": "earnings_growth",
                "min": 0.10,
                "max": None,
                "weight": 2.0,
                "description": "EPS 성장률 ≥ 10%",
                "format": ".1%",
            },
            {
                "name": "순이익마진",
                "field": "profit_margins",
                "min": 0.10,
                "max": None,
                "weight": 1.5,
                "description": "순이익률 ≥ 10%",
                "format": ".1%",
            },
            {
                "name": "ROE",
                "field": "roe",
                "min": 0.15,
                "max": None,
                "weight": 1.5,
                "description": "ROE ≥ 15%",
                "format": ".1%",
            },
            {
                "name": "P/E",
                "field": "pe",
                "min": 0,
                "max": 50,
                "weight": 1.0,
                "description": "PER ≤ 50 (성장프리미엄 허용)",
                "format": ".1f",
            },
        ],
    },
}

FIELD_LABELS = {
    "pe": "PER",
    "forward_pe": "Forward PER",
    "pb": "PBR",
    "roe": "ROE",
    "debt_to_equity": "D/E(%)",
    "current_ratio": "유동비율",
    "dividend_yield": "배당수익률",
    "earnings_growth": "EPS성장률",
    "revenue_growth": "매출성장률",
    "profit_margins": "순이익률",
    "peg": "PEG",
    "ev_ebitda": "EV/EBITDA",
    "market_cap": "시가총액",
    "price": "현재가($)",
}
